HPCC-26749 Fix storage account
hpcc-systems/terraform-azurerm-hpcc pull request #1
Opened 2021-12-07 16:17 UTC by gfortil

Signed-off-by: Godson Fortil <godson.fortil@lexisnexisrisk.com>

Fix overlapping CIDRs for Vnet peering

Signed-off-by: Godson Fortil <godson.fortil@lexisnexisrisk.com>

HPCC-26749 Fix storage account network issue

Signed-off-by: Godson Fortil <godson.fortil@lexisnexisrisk.com>

Adds examples/admin.tfvars for storage account and virtual network

Signed-off-by: Godson Fortil <godson.fortil@lexisnexisrisk.com>

Comment optional arguments out in admin.tfvars

Signed-off-by: Godson Fortil <godson.fortil@lexisnexisrisk.com>

HPCC-26749 Fix storage account

Signed-off-by: Godson Fortil <godson.fortil@lexisnexisrisk.com>

2021-12-07 19:46 UTC, stuartort commented on examples/admin.tfvars
> +  # location    = "eastus"
if location is not needed, remove it instead of commenting it out.  If it is needed in certain situations, let's add a comment and/or add to README file

2021-12-07 19:58 UTC, stuartort commented on modules/storage_account/LICENSE
> +MIT License
Shouldn't we be using the standard LN license info that we use in our other file

2021-12-08 07:46 UTC, gfortil commented on examples/admin.tfvars
> +  # location    = "eastus"
It is used in one case, but I will simplify it by using the one in the virtual_network block.

2021-12-08 07:50 UTC, gfortil commented on modules/storage_account/LICENSE
> +MIT License
The LN opensource TF repos are MIT licensed. What do you think @richardkchapman ?

2021-12-08 21:52 UTC, stuartort commented
running through this again, it seems to work fine.  @Michael-Gardner can you review the code

2022-01-31 22:06 UTC, gfortil commented
@Michael-Gardner @lorraineachapman could you please review?

2022-02-07 10:56 UTC, AttilaVamos requested changes

2022-02-07 10:56 UTC, AttilaVamos commented on examples/admin.tfvars
> +  timeout = 340
If ELK is enabled (by my experience) it needs some larger timeout (e.g.: "timeout=900" in my case)

2022-02-07 10:56 UTC, AttilaVamos commented on examples/admin.tfvars
>    # chart  = ""
By my experiences it needs some timeout ("  timeout = 900") to safe and successful start.

2022-02-07 10:56 UTC, AttilaVamos commented on locals.tf
>    elk_repository     = "https://github.com/hpcc-systems/helm-chart/raw/master/docs/elastic4hpcclogs-1.0.0.tgz"
I changed it to "https://github.com/hpcc-systems/helm-chart/raw/master/docs/elastic4hpcclogs-1.2.0.tgz" however it is possible there is a newer version (OK, I see Rodrigo has a PR for this.)

2022-02-08 18:45 UTC, gfortil commented on examples/admin.tfvars
>    # chart  = ""
that can be set by the user using the timeout argument

2022-02-08 18:46 UTC, gfortil commented on locals.tf
>    elk_repository     = "https://github.com/hpcc-systems/helm-chart/raw/master/docs/elastic4hpcclogs-1.0.0.tgz"
I will add the ability to set the ELK version as an optional in a future PR

2022-02-09 13:30 UTC, richardkchapman commented
Needs rebasing for a clean merge

2022-02-09 14:48 UTC, gfortil commented on examples/admin.tfvars
> +  timeout = 340
That will always vary for some users. 600 seconds is usually more than enough for me.

2022-02-09 16:25 UTC, Michael-Gardner approved these changes
Minor changes and clarifications. Looks really good.

2022-02-09 16:25 UTC, Michael-Gardner commented on README.md
> +This module is intended as an example for development and test systems only. It can be used as a blueprint to develope your own production version that meets your organization's security requirements
develope should be develop.

2022-02-09 16:25 UTC, Michael-Gardner commented on locals.tf
>    storage_repository = "https://github.com/hpcc-systems/helm-chart/raw/master/docs/hpcc-azurefile-0.1.0.tgz"
do we not need different versions of these charts depending on the hpcc version we're using? Just asking for clarification.

2022-02-09 17:00 UTC, gfortil commented on locals.tf
>    storage_repository = "https://github.com/hpcc-systems/helm-chart/raw/master/docs/hpcc-azurefile-0.1.0.tgz"
I was planning on issuing a different PR for that. I'll include it in this one since I'm rebasing.

2022-02-10 21:04 UTC, closed without merging