HPCC-28035 add initial github action for terraform CI
hpcc-systems/terraform-azurerm-hpcc pull request #17
Opened 2022-08-09 02:55 UTC by xwang2713

The github action tf-ci.yml will do followings:

1. Login Azure with Service Principal
2. Apply module/virtual_network
3. Apply module/storage_account
4. Apply Kubernetes/HPCC
5. Run a simple ECL test and parse the result
6. Destroy Kubernetes/HPCC
7. Destroy module/storage_account
8. Destroy module/virtual_network

The code tested in xwang2713/terraform-azurerm-hpcc-aks branch az-devops
In order to test in hpcc-systems/terraform-azurerm-hpcc main following need update:
Azure Portal/Azure Active Directory/App Registration/
 ris-azr-app-us-hpccplatform-dev-github | Certificates & secrets |Federated credentials
Change github organization to "hpcc-systems" and Repository to "terraform-azurerm-hpcc"

Assigned off by xiaoming.wang@lexisnexis.com

2022-08-11 20:50 UTC, gfortil requested changes

2022-08-17 01:22 UTC, xwang2713 commented on .github/workflows/README.md
> +### Virtual Network Terraform Destroy May Fail
I change to 
   If any HPCC or Storage Account resource is not destroyed Virtual Network can't be destroyed. Manually delete HPCC and Storage Account resources first then manually delete the resource group with admin field which defined in admin.name in devops/vnet.tfvars

2022-08-17 01:24 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +name: Terraform Continue Integration
Fixed

2022-08-17 01:28 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +      ARM_CLIENT_SECRET: ${{ secrets.SERVICE_PRINCIPAL_VALUE }}
I change it to "ARM_SERVICE_PRINCIPAL_SECRET". I don't find anything start with "ARM_" in terraform-azurerm-hpcc repo.
Not sure how it is used.

2022-08-17 01:29 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +    - name: 'Az CLI login'
We need "Az CLI login" otherwise we have all kind of authorization issues

2022-08-17 01:33 UTC, xwang2713 commented on devops/test/basic/simple.ecl
> +/*
Don't know what to do

2022-08-17 01:33 UTC, xwang2713 commented on devops/test/docker-run.sh
> +#!/usr/bin/env bash
Don't know what to do

2022-08-17 01:35 UTC, xwang2713 commented on devops/azure/pipelines/pipeline-vnet.yaml
> +# Azure DevOps pipeline for Azure deployment
I will change it. But this is for Azure DevOps which we don't have license. I just leave the code for future

2022-08-17 01:38 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +name: Terraform Continue Integration
We name all executables with '-' instead of '_' which is recommended for latest Linux

2022-08-17 01:46 UTC, xwang2713 commented on devops/terraform/hpcc-versions.tf
> +terraform {
Change:
hpcc versions.tf:  version = "=2.99.0"
sc versions.tf:      version = "~> 3.0"
vnet versions.tf   version = ">=3.16.0"

2022-08-17 01:50 UTC, xwang2713 commented
@gfortil :  I check in the update.  After everything is OK I will rebase to make it looks like one commit

2022-08-17 18:09 UTC, gfortil commented on .github/workflows/README.md
> +### Virtual Network Terraform Destroy May Fail
The only resources that need to be destroyed are those on the VNet, for instance the AKS. The storage accounts are not on the VNet nor in the same resource group as the VNet.

2022-08-17 18:13 UTC, gfortil commented on devops/test/basic/simple.ecl
> +/*
I meant you should probably  add "s" to test since we plan on having multiple sets of tests

2022-08-17 18:13 UTC, gfortil commented on devops/test/docker-run.sh
> +#!/usr/bin/env bash
I meant you should probably add "s" to test since we plan on having multiple sets of tests

2022-08-17 18:15 UTC, gfortil commented on devops/azure/pipelines/pipeline-vnet.yaml
> +# Azure DevOps pipeline for Azure deployment
ok

2022-08-18 14:18 UTC, xwang2713 commented on .github/workflows/README.md
> +### Virtual Network Terraform Destroy May Fail
I know. so I destroy in order:  AKS/HPCC,  Storage_Count and VirtualNetwork at the end

2022-08-18 15:49 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +    - name: Initialize VNet erraform
Fixed

2022-08-18 15:59 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +    - name: Prepare SC Terraform files
Replace SC with "Storage Account" and sc to sa. Also rename files scxx to saxx under devops/terraform/

2022-08-18 16:02 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +    - name: Initialize SC Terraform
Fixed

2022-08-18 16:03 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +    - name: Apply SC Terraform
Fixed

2022-08-18 16:05 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +      #if: always()
It is for debug before. I delete it

2022-08-18 16:07 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +    #    failed_pods=$(kubectl get pod | grep -v "1/1" | grep -v "2/2" | grep -v "NAME" || true) &&
That is for checking if all pods are ready, i.e. "1/1" or "2/2". But I thought terraform module will check it so I don't need duplicate. Leave it in chance we want add similar code in future

2022-08-18 16:14 UTC, xwang2713 commented on .github/workflows/tf-ci.yml
> +    - name: Destroy SC Terraform
Fixed

2022-08-18 16:28 UTC, xwang2713 commented on devops/terraform/hpcc-locals.tf
> +locals {
cp ${{ github.workspace }}/devops/terraform/hpcc-locals.tf \
         ${{ github.workspace }}/locals.tf

Not sure if hpcc-locals.tf differs from default locals.tf or not. We add something before but maybe deleted already.
If you change locals.tf I can re-exam hpcc-locals.tf

2022-08-18 16:35 UTC, xwang2713 commented on devops/terraform/hpcc-providers.tf
> +provider "azurerm" {
Both "_" and "-" are OK. The new trend is to use "-" like all HPCC Platform scripts and related files
We just shouldn't mix these two

2022-08-18 16:43 UTC, xwang2713 commented on devops/terraform/hpcc-versions.tf
> +terraform {
I message you about this

2022-08-18 16:46 UTC, xwang2713 commented on devops/terraform/hpcc-versions.tf
> +      #version = "<=2.99.0"
Fixed for hpcc-versions.tf, sa-versions.tf and vnet-versions.tf

2022-08-18 16:47 UTC, xwang2713 commented on devops/terraform/sc-providers.tf
> +provider "random" {
I keep it as sa-providers.tf. We can decide if want to use "_"

2022-08-18 16:47 UTC, xwang2713 commented on devops/terraform/sc-versions.tf
> +terraform {
The same as above

2022-08-18 16:50 UTC, xwang2713 commented on devops/terraform/sc-versions.tf
> +terraform {
Fixed

2022-08-18 16:50 UTC, xwang2713 commented on devops/terraform/vnet-providers.tf
> +provider "random" {
will discuss

2022-08-18 16:50 UTC, xwang2713 commented on devops/terraform/vnet-versions.tf
> +terraform {
The same

2022-08-18 18:04 UTC, gfortil commented on devops/terraform/hpcc-locals.tf
> +locals {
It's ok to add whatever is in hpcc-locals.tf to locals.tf
The less duplicates the easier it is to keep track of future changes

2022-08-22 12:52 UTC, xwang2713 commented on devops/test/basic/simple.ecl
> +/*
changed

2022-08-22 12:54 UTC, xwang2713 commented on devops/test/docker-run.sh
> +#!/usr/bin/env bash
changed

2022-08-22 12:58 UTC, xwang2713 commented on devops/terraform/hpcc-locals.tf
> +locals {
remove hpcc-locals.tf and update tf-ci.yml

2022-08-22 13:00 UTC, xwang2713 commented on devops/terraform/vnet-versions.tf
> +terraform {
vnet-verions.tf and modules/virtual-network/versions.tf match

2022-08-22 13:01 UTC, xwang2713 commented on devops/test/basic/run.sh
> +#!/bin/bash
changed

2022-08-22 13:04 UTC, xwang2713 commented
@gfortil updated. Again I will rebase after everything looks good

2022-08-24 16:25 UTC, merged